version: 2

sources:
  - name: backend_tables
    tables:
      - name: nkb_jobs_userplacementdetails
      - name: nkb_placement_support_placementsection
      - name: nkb_placement_support_placementsectionstep
      - name: nkb_placement_support_placementsectionstepresource
      - name: nkb_placement_support_userplacementsection
      - name: nkb_placement_support_userplacementstepchecklist
      - name: nkb_placement_support_userplacementstepinterview
      - name: nkb_placement_support_userplacementstepvideosubmission
      - name: nkb_placement_support_userresume
      - name: nkb_placement_support_uservideosubmissionevaluation
      - name: nkb_resources_userresource
      - name: xpm_ccbp_users_master_db_view
      - name: user_data_for_incremental_model
      - name: placement_status_null_enum


 